version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: assignment-db
    environment:
      POSTGRES_DB: assignment
      POSTGRES_USER: ankit
      POSTGRES_PASSWORD: 9658523363
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ankit -d assignment"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: assignment-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data: